### ISSUE TITLE
Feature request: Parse all URLs or links that may be assets

### ISSUE THREAD

**Issue by kdheepak** [bluwy/svelte-preprocess-import-assets#7] opened 2022-02-04 09:34 UTC
One issue that I'm running into is the following:

My source markdown looks like this:

```
![vimtutor](./videos/vimtutor.webm){ width=100% loop="true" autoplay="true" }
```

And the following gets generated from the above markdown:

```
<video src="./videos/vimtutor.webm" loop autoplay style="width:100.0%" controls><a href="./videos/vimtutor.webm">vimtutor</a></video>
```

When running it through this svelte-preprocess-import-assets, the following gets generated:

```
<video src="{___ASSET___0}" loop autoplay style="width:100.0%" controls><a href="./videos/vimtutor.webm">vimtutor</a></video>
```

Ideally, it would become 

```
<video src="{___ASSET___0}" loop autoplay style="width:100.0%" controls><a href="{___ASSET___0}">vimtutor</a></video>
```

___

More generally, right now if I have the following markdown source:

```
This is a [link to an image](./images/example.png)

![rendered image](./images/example.png)
```

i.e. the following HTML source

```
<p>This is a <a href="./images/example.png">link to an image</a></p>

<figure>
<img src="./images/example.png" alt="rendered image">
<figcaption aria-hidden="true">rendered image</figcaption>
</figure>
```

When running through this `svelte-preprocess-import-assets`, the following gets generated:

```
<script>import ___ASSET___0 from "./images/example.png";</script>
<p>This is a <a href="./images/example.png">link to an image</a></p>
<figure>
<img src="{___ASSET___0}" alt="rendered image">
<figcaption aria-hidden="true">rendered image</figcaption>
</figure>
```

This results in the link not working even though the image is rendered correctly.

It would be nice if all links to the same asset are replaced with the imported asset.

Feel free to close if you think this is out of scope for this plugin.

**Comment by bluwy** [comment] 2022-02-05 08:32
This one's tricky since the preprocessor currently doesn't check `a` tag at all as it may contain any link that's not necessarily an asset. If we do want to check the `a` tag, we would have to keep a list of known asset extensions and go from there, but yes I think this is going out of scope of the preprocessor.

For now, you should be able to still get it working with a custom source like:
```js
{
  sources: (defaultSources) => {
    return [
      ...defaultSources,
      {
        tag: 'a',
        srcAttributes: ['href'],
        filter: ({ value }) => /\.(png|jpg|gif|webm)$/.test(value)
      },
    ]
  },
}

**Comment by bluwy** [comment] 2022-02-08 06:03
Closing this as intended behaviour for now

**Closed by bluwy** 2022-02-08 06:03 UTC
